//go:build ignore

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const module = "github.com/xrk-agt/goserver"

func main() {
	apisDir := filepath.Join("apis")
	entries, err := os.ReadDir(apisDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read apis: %v\n", err)
		os.Exit(1)
	}

	var imports []string
	for _, e := range entries {
		name := e.Name()
		if !e.IsDir() || strings.HasPrefix(name, "_") || name == "system" {
			continue
		}
		imports = append(imports, fmt.Sprintf("\t_ %q", module+"/apis/"+name))
	}

	outPath := filepath.Join("core", "plugin_imports_gen.go")
	f, err := os.Create(outPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "create %s: %v\n", outPath, err)
		os.Exit(1)
	}
	defer f.Close()

	fmt.Fprintln(f, "package core")
	fmt.Fprintln(f)
	fmt.Fprintln(f, "// Code generated by tools/gen_plugin_imports.go; DO NOT EDIT.")
	fmt.Fprintln(f, "import (")
	for _, imp := range imports {
		fmt.Fprintln(f, imp)
	}
	fmt.Fprintln(f, ")")
	fmt.Fprintf(os.Stderr, "wrote %s (%d plugins)\n", outPath, len(imports))
}
